version: "3.9"

services:

  petstoreapp:
    build:
      context: ./petstoreapp
    image: pscr.azurecr.io/petstoreapp:latest
    ports:
      - "8080:8080"
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://petstorepetservice:8081
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - PETSTOREORDERSERVICE_URL=http://petstoreorderservice:8083
    networks:
      - petstorebridge

  petstorepetservice:
    build:
      context: ./petstorepetservice
    image: pscr.azurecr.io/petstorepetservice:latest
    ports:
      - "8081:8081"
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
    networks:
      - petstorebridge

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    image: pscr.azurecr.io/petstoreproductservice:latest
    ports:
      - "8082:8082"
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082
    networks:
      - petstorebridge

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    image: pscr.azurecr.io/petstoreorderservice:latest
    ports:
      - "8083:8083"
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
    networks:
      - petstorebridge

networks:
  petstorebridge:
    driver: bridge
