bing:
  search:
    subscription:
      key: ${BING_SEARCH_SUBSCRIPTION_KEY:}
petstore:
  service:
    pet:
      url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
  logging:
    additional-headers-to-log: ${PETSTORE_ADDITIONAL_HEADERS_TO_LOG:}
    additional-headers-to-send: ${PETSTORE_ADDITIONAL_HEADERS_TO_SEND:}
  signalR:
    negotiation-url: ${SIGNALR_NEGOTIATION_URL:}
    service-url: ${SIGNALR_SERVICE_URL:}
    key: ${SIGNALR_SERVICE_KEY:}
    update:
      fixedRate: ${SIGNALR_UPDATE_FIXEDRATE:60000}
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers]
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: 'true'
          oidc-enabled: 'true'
          base-uri: 'https://cloudxpetstore.b2clogin.com/cloudxpetstore.onmicrosoft.com/'
          tenant: ${PETSTOREAPP_TENANT}
          login-flow: sign-up-or-sign-in
          credential:
            client-id: ${PETSTOREAPP_CLIENT_ID}
            client-secret: ${PETSTOREAPP_CLIENT_SECRET}
          logout-success-url: ${PETSTOREAPP_LOGOUT_URL}
          user-name-attribute-name: sub
          user-flows:
            sign-up-or-sign-in: 'B2C_1_signupsignin'
            profile-edit: 'B2C_1_profileediting'
            password-reset: 'B2C_1_passwordreset'

azure:
  application-insights:
    instrumentation-key: ${PETSTOREAPP_AI_INSTRUMENTATION_KEY:}