springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREPETSERVICE_SERVER_PORT:8080}

azure:
  keyvault:
    uri: "https://cloudx-petstore-keyvault.vault.azure.net/"
    tenant-id: ${TENANT_ID}
    managed-identity: ${SERVICE_ACCOUNT}
  
spring:
  application:
    name: petstorepetservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${PGDBURL-PET}
    username: ${PGDBUSER}
    password: ${PGDBPASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
