name: CI/CD to Azure Container Registry

env:
  AZURE_CONTAINER_REGISTRY: cloudxpsacr.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: cloudxpsacr
  TAG: v${{ github.run_number }}

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build Docker Compose stack
      run: docker compose -f docker-compose.yml build

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.PETSTORESECRET }}

    - name: Build and push Docker image to Azure Container Registry
      run: docker compose -f docker-compose.yml push