springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
  cosmosdb:
    accountkey: ${COSMOSDB_ACCOUNT_KEY:}
    accounthost: ${COSMOSDB_ACCOUNT_HOST:}
    database: ${COSMOSDB_DATABASE:}
    container: ${COSMOSDB_CONTAINER:}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
